services:
  - type: web
    name: realestate-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd fastapi-backend && uvicorn app_fastapi:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: API_KEY
        value: AIzaSyCkR5iY6QbeZ04zxOwazQH3EFsiX-kf1KI

  - type: web
    name: realestate-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
