services:
  - type: web
    name: fastapi-backend
    env: python
    runtime: python-3.11
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app_fastapi:app --host 0.0.0.0 --port $PORT"
